project:
  type: website

website:
  title: "NASA-Openscapes"
  site-url: https://nasa-openscapes.github.io/
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/) and with inspiration from the [UCSB MEDS website](https://ucsb-meds.github.io/)"
    left: "&copy; CC-By Openscapes Core Team"
 
  navbar:
    logo: openscapes_hex.png
    href: https://openscapes.org
    right:
      - text: "Events"
        href: index.html
      - text: "Home"
        href: https://openscapes.org
      - icon: github
        href: https://github.com/openscapes/events
      - icon: twitter
        href: https://twitter.com/openscapes
        
format:
  html:
    theme: 
      - lumen 





# name: "."
# title: "NASA-Openscapes"
# description: |
#   NASA-Openscapes
# favicon: images/openscapes_hex.png  
# output_dir: "docs"
# navbar:
#   logo: images/openscapes_hex.png
#   href: https://openscapes.org
#   right:
#     - text: "Home"
#       href: index.html
#     - text: "About"
#       href: about.html
#     - text: "Mentors"
#       href: mentors.html
#     - text: "Champions"
#       href: champions.html 
#     - text: "Tutorials"
#       href: tutorials.html 
#     - text: "Events"
#       href: events.html
#     - icon: fab fa-twitter
#       href: https://twitter.com/openscapes
#     - icon: fab fa-github
#       href: https://github.com/nasa-openscapes
# output: distill::distill_article
# theme: theme.css