---
title: "Events"
description: |
  Events and News from the NASA-Openscapes Framework Project 
---

See also [slides listed on the About page](https://nasa-openscapes.github.io/about.html#slides) that have been presented about NASA Openscapes at conferences and workshops.

## Fall 2023: Mentors give workshops at AGU

December 11 - 15, NASA Openscapes Mentors will attend the AGU annual meeting and deliver workshops. High-level planning happens in the [2023-planning-agu](https://github.com/NASA-Openscapes/2023-planning-agu) GitHub repo.


## Summer 2023: Mentors Retreat at ESIP

The July 17 NASA Openscapes Mentors Retreat will bring together mentors from across seven+ DAACs that have engaged as leaders in the NASA Openscapes project.  We see the main value of this retreat as a chance to solidify these cross-DAAC relationships, share lessons learned, problem solve, and ignite new collaborations across the DAACs.

Over the last two years, the mentors have built a community across DAACs, created resources in the Earthdata Cloud Cookbook and supported early adopter users migrating their workflows to the cloud. The goal of the 1-day retreat is to plan the long-term sustainability of the Mentors community from both the governance and technical side.

The NASA Openscapes Mentor Retreat will be in Burlington, Vermont on Monday, July 17 before the [ESIP Summer Meeting, July 18-21](https://www.esipfed.org/meetings). We will also provide the opportunity for the Mentors to attend the ESIP Meeting in order to network and learn from the broader community. All registration, travel, accommodation, per diems will be covered.


## Spring 2023

### April-June 2023: Openscapes Champions Cohort

See <https://nasa-openscapes.github.io/champions> for more details!

## Winter 2023

### March 2023: ESDSWG

Details soon

### March 2023: Women in Data Science Conference

<https://www.widsconference.org/> 

We will share how we developed the Openscapes Flywheel to support the NASA DAAC Mentors, and some of their acheivements and momentum!

### February 2023: EMIT Workshop

<https://github.com/nasa/EMIT-Data-Resources>

This workshop was designed to be completed locally, however it was offered to use the Openscapes 2i2c JupyterHub cloud workspace to revisit the EMIT Data Tutorials Workshops hosted February 3, 10, and 17th 2023. The Feb 17th event had 91 active users in large python instances in the 2i2c JupyterHub; Aaron Friesz, Bri Lind (LP DAAC) and Luis Lopez (NSIDC) worked ahead of time with 2i2c engineers to accommodate the increased CPU needs for this workshop.


### January 2023: ESIP 

NASA Openscapes is involved with 3 talks on Tuesday and Wednesday. We're looking forward to seeing you at these and other ESIP sessions: 

- Amy Steiker speaking in [Enabling Open Science with NASA's Earthdata in the Cloud](https://2023januaryesipmeeting.sched.com/event/1EwXE/enabling-open-science-with-nasas-earthdata-in-the-cloud)
- Julie Lowndes speaking in [Earth and Space Science Knowledge Commons: From vision to implementation](https://2023januaryesipmeeting.sched.com/event/1EwXQ/earth-and-space-science-knowledge-commons-from-vision-to-implementation)
- Brianna Pagan speaking in [Bringing Cloud-Native Science “Down To Earth”](https://2023januaryesipmeeting.sched.com/event/1EwXf/bringing-cloud-native-science-down-to-earth)
- Luis Lopez and Cassie Nickles speaking in [Better science for future us: Openscapes stories and approaches for the Year of Open Science](https://2023januaryesipmeeting.sched.com/event/1EwXx/better-science-for-future-us-openscapes-stories-and-approaches-for-the-year-of-open-science)

## Fall 2022

### American Geophysical Union (AGU) Fall Conference

3 posters, hackathon, and plenary lightning talk! 

## Summer 2022

[Keynote at RStudio Conference - “Hello Quarto: share • collaborate • teach • reimagine”](rstudio.com/conference/2022/keynotes/collaborate-with-quarto). We shared how we support NASA Earthdata DAACs as part of the global launch of Quarto, an open source publishing framework that we contributed to as first external users and has been a big part of “place” - having a place to collaborate across the DAACs. Blog post with link to slides and video: <https://openscapes.org/blog/2022/08/10/quarto-keynote>

## Spring 2022  


### April 2022 ECOSTRESS Workshop

Point of contact: Aaron Friesz

<https://nasa-openscapes.github.io/2022-ECOSTRESS-Cloud-Workshop/>

### March 2022 GES DISC Internal Cloud Workshop

Point of contact: Alexis Hunzinger

### March 2022. PO.DAAC SWOT Oceanography Workshop

Point of contact: Catalina Oaida

<https://podaac.github.io/2022-SWOT-Ocean-Cloud-Workshop/>

### March 2022. Earthdata Cloud Services Working Group

Point of contact: Amy Steiker

<https://nasa-openscapes.github.io/earthdata-cloud-cookbook/examples/Transform-workflow.html>


### March-April 2022. Openscapes Champions Cohort

NASA Openscapes Champions is a mentorship and professional development opportunity for research teams using data from NASA Distributed Active Archive Centers (DAACs) and interested in open science and migrating their analytical workflows to the cloud. Learn more and nominate your team: <https://nasa-openscapes.github.io/champions>.

## 2021

**January 21, 2021. ESIP**  
We are leading a session at ESIP's Winter Meeting: 
[Better Science for Future Us: Planning for the Year of Open Science](https://2022esipjanuarymeeting.sched.com/event/qkp5/better-science-for-future-us-planning-for-the-year-of-open-science). 

**Blog summary**:

- <https://www.openscapes.org/blog/2022/02/17/esip-winter-2022>

**December 12 2021. AGU Fall Meeting Workshop (Virtual)** \
NASA's Earth Science Data Systems (ESDS) Program promotes open data access for open science. The workshop will highlight novel applications that utilize EOSDIS data in the cloud. Participants will leave having a better understanding of how NASA Earthdata Cloud data and services can best be leveraged and integrated within their work across a variety of disciplines and data types. Details: <https://agu.confex.com/agu/fm21/meetingapp.cgi/Session/124026>; <https://nasa-openscapes.github.io/2021-Cloud-Workshop-AGU/> <br>

**November 15-19 2021. Cross-DAAC Cloud Hackathon** \
The NASA-Openscapes Framework is part of a collaborative Cross-DAAC hackathon to help transition workflows to the cloud. All details and tutorials are available at: <https://nasa-openscapes.github.io/2021-Cloud-Hackathon/><br>

**Blog summaries**:

- <https://earthdata.nasa.gov/learn/articles/2021-cloud-hackathon>
- <https://podaac.jpl.nasa.gov/announcements/2021-12-15-The-2021-Cloud-Hackathon>

**August-September 2021. DAAC User Working Group Presentations**\
The NASA-Openscapes Framework is being shared at DAAC User Working Group meetings including:

-   LP DAAC, August 12, 2021 ([Slides](https://docs.google.com/presentation/d/1SVwkEDe2gUzJJZ5NGsGTsGPde-NJm9HLtKieSeuthfI/edit))

-   GES DISC, September 8, 2021

-   NSIDC DAAC, September 16, 2021<br>

**June 30, 2021. NASA Openscapes Framework presented at Pangeo Showcase**\
Our project was presented at the Pangeo Showcase, a weekly webinar that highlights relevant work around the Python/Earth science community. The talk and slides can be found on [their website](https://discourse.pangeo.io/t/june-30-2021-the-nasa-openscapes-framework/1631). <br>

**June 21-24, 2021. Carpentries Instructor Training**\
This is the suggested session for Carpentries Instructor training for the Mentor Cohort. Mentors can also attend later events. <br>

**May 17-18, 2021. Carpentries Workshop: Intro to Linux/Shell, Python, Git**\
This workshop is open to NASA Earth science data users, hosted by Openscapes, NASA, and the NASA Atmospheric Science Data Center (ASDC) DAAC.\
For more information and to register: <https://virdi.github.io/2021-05-17-openscapes-online/> <br>

**March 2021 - Feb 2021. Openscapes Champions Mentors: DAAC Cohort**\
We are supporting and strengthening the community of DAAC folks that are already creating cloud learning resources. Through Openscapes mentorship, Carpentries instructor training, and 2i2c cloud services, these DAAC mentors will work together to create learning resources for their teams and communities. <br>

**Feb 2021. Openscapes and Collaborators Announce Openscapes NASA Project** \
We are thrilled to announce that NASA awarded Openscapes and partners a 3-year project to utilize the Openscapes Framework and support researchers using NASA Earthdata as it moves to the cloud. [Openscapes](https://www.openscapes.org/blog/2021/03/10/nasa-announcement/) and it's host institution, [NCEAS](https://www.nceas.ucsb.edu/news/nasa-openscapes), [Metadata Game Changers](https://metadatagamechangers.com/blog/2021/3/10/metadata-game-changers-partners-with-openscapes-in-new-nasa-funded-project) and [NASA's Earthdata Blog](https://earthdata.nasa.gov/learn/articles/openscapes) all shared posts about the award.
