name: Render and deploy quarto files
on: 
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "Install Quarto"
      uses: quarto-dev/quarto-actions/install-quarto@main
      with:
        version: 0.9.105
      
    - name: "Quarto render"
      shell: bash
      run: |
        quarto render --execute-debug      
        
    - name: "Deploy to gh-pages"
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
